name = "PROJECT DEADZONE"
author = "PROJECT DEADZONE Team"
version = "R4-packwiz-20260809"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a51a62fec1e84879f4c542eb8fc52adf7bcdb2068add71c673cc4b3600bd7d42"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
