name = "PROJECT DEADZONE"
author = "PROJECT DEADZONE Team"
version = "BETA-20260911-JOB-UI-RECRUITS-REMOVAL-HOTFIX"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d7e7bbe6caf9737c146cd1fa428b9280b7cbbc13b78491735d8e576f628f3cc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
