// PROJECT DEADZONE certified life-supply lots v0.1

StartupEvents.registry("item", event => {
  event.create("seasonal_supply_lot_standard")
    .displayName("§f標準・旬の供給ロット")
    .texture("layer0", "minecraft:item/wheat")
    .maxStackSize(16)
  event.create("seasonal_supply_lot_select")
    .displayName("§a選別・旬の供給ロット")
    .texture("layer0", "minecraft:item/carrot")
    .rarity("uncommon")
    .maxStackSize(16)
  event.create("seasonal_supply_lot_prime")
    .displayName("§b特選・旬の供給ロット")
    .texture("layer0", "minecraft:item/golden_carrot")
    .rarity("rare")
    .maxStackSize(16)

  event.create("catch_lot_standard")
    .displayName("§f標準・漁獲ロット")
    .texture("layer0", "minecraft:item/cod")
    .maxStackSize(16)
  event.create("catch_lot_select")
    .displayName("§a選別・漁獲ロット")
    .texture("layer0", "minecraft:item/salmon")
    .rarity("uncommon")
    .maxStackSize(16)
  event.create("catch_lot_prime")
    .displayName("§b特選・漁獲ロット")
    .texture("layer0", "minecraft:item/tropical_fish")
    .rarity("rare")
    .maxStackSize(16)
})

