StartupEvents.registry('item',event=>{
  event.create('affix_scrap_common')
    .displayName('Affix Scrap')
    .texture('kubejs:item/affix_scrap_common')
    .tooltip('§7損傷した装備から回収した機械部品。Common Affixの加工に使う。')
  event.create('affix_scrap_uncommon')
    .displayName('Refined Affix Circuit')
    .texture('kubejs:item/affix_scrap_uncommon')
    .tooltip('§a選別・精製済みの回路部品。Uncommon Affixの加工に使う。')
  event.create('affix_scrap_rare')
    .displayName('Rare Affix Core')
    .texture('kubejs:item/affix_scrap_rare')
    .tooltip('§b安定した演算コア。Rare Affixの付与と再構成に使う。')
  event.create('affix_scrap_epic')
    .displayName('Epic Affix Matrix')
    .texture('kubejs:item/affix_scrap_epic')
    .tooltip('§d高密度の演算結晶。Epic Affixの再構成に使う。')
    .glow(true)
  event.create('affix_scrap_legendary')
    .displayName('WARDEN Command Core')
    .texture('kubejs:item/affix_scrap_legendary')
    .tooltip('§6自律機械の中枢部品。Legendary Affixの再構成に使う。')
    .glow(true)
})
