# PROJECT DEADZONE grave safety defaults
enable_obituary = true
replaceable_blocks = ["#gravestone:grave_replaceable"]
remove_obituary = false
only_owners_can_break = false
spawn_ghost = false
friendly_ghost = true
sneak_pickup = false
break_pickup = true
strict_placement = true
