["Sling Delays (in Ticks)"]
	#Tier 1 Draw Time
	#Range: 0 ~ 100
	tier1_draw = 18
	#Tier 1 Store Time
	#Range: 0 ~ 100
	tier1_store = 10
	#Tier 1 Swap Time
	#Range: 0 ~ 100
	tier1_swap = 14
	#Tier 2 Draw Time
	#Range: 0 ~ 100
	tier2_draw = 14
	#Tier 2 Store Time
	#Range: 0 ~ 100
	tier2_store = 8
	#Tier 2 Swap Time
	#Range: 0 ~ 100
	tier2_swap = 11
	#Tier 3 Draw Time
	#Range: 0 ~ 100
	tier3_draw = 10
	#Tier 3 Store Time
	#Range: 0 ~ 100
	tier3_store = 6
	#Tier 3 Swap Time
	#Range: 0 ~ 100
	tier3_swap = 8
	#Tier 4 Draw Time
	#Range: 0 ~ 100
	tier4_draw = 7
	#Tier 4 Store Time
	#Range: 0 ~ 100
	tier4_store = 4
	#Tier 4 Swap Time
	#Range: 0 ~ 100
	tier4_swap = 6
