#Just debug mode
TankSlamRange = 5.0
#Just debug mode
TankSpinRange = 5.0
#Just debug mode
TankSlamDamage = 6.0
#Just debug mode
TankSpinDamage = 6.0
#Just debug mode
TankPreSpinTicks = 40.0
#Just debug mode
TankSpinDurationTicks = 75.0
#Just debug mode
TankSpinDamageCheckTicksInterval = 5.0
#Just debug mode
TankSpinBlindnessDuration = 30.0
#Just debug mode
TankSpinBlindnessLevel = 2.0
#Just debug mode
TankSpinSlownessDuration = 40.0
#Just debug mode
TankSpinSlownessLevel = 3.0
#Just debug mode
TankSpinStunDuration = 30.0
#Just debug mode
TankSlamBlindnessDuration = 20.0
#Just debug mode
TankSlamBlindnessLevel = 2.0
#Just debug mode
TankSlamSlownessDuration = 45.0
#Just debug mode
TankSlamSlownessLevel = 3.0
#Just debug mode
TankSpinKnockback = 2.0
#Just debug mode
TankSpinKnockbackUp = 0.4
#Just debug mode
TankSlamKnockback = 1.5
#Just debug mode
TankSlamKnockbackUp = 0.3
#Just debug mode
#Range: > -2147483648
SpawnWeight = 7
#Just debug mode
#Range: > -2147483648
SpawnMinCount = 1
#Just debug mode
#Range: > -2147483648
SpawnMaxCount = 2

