[hearts]

	[hearts.health]

		[hearts.health.icons]
			style = "VANILLA"
			lastHeartOutline = false

		[hearts.health.tanks]
			enabled = false

		[hearts.health.text]
			style = "DISABLED"

	[hearts.absorption]

		[hearts.absorption.icons]
			style = "VANILLA"

		[hearts.absorption.text]
			style = "DISABLED"
