
#Client configuration settings
[client]

	#Configuration options for debugging vehicles
	[client.debug]
		#If true renderes animations of vehicles dooing a wheelie or releasing charge
		renderWheelieAnimation = true
		#If true, renders an outline of all the elements on a vehicle's model. Useful for debugging interactions.
		renderOutlines = false
		#If true, renders lines to help visualise steering direction and target position.
		renderSteeringDebug = false
		#If true, the raytracer will be reloaded each tick.
		reloadRaytracerEachTick = false
		#If true, the vehicle properties will be reloaded each tick.
		reloadVehiclePropertiesEachTick = false
		#If true, when rendering debug outlines all interactables boxes will be rendered rather than just the active
		forceRenderAllInteractableBoxes = false
		#Enables use of debug camera tools
		debugCamera = false

	#Configuration options for vehicle interaction
	[client.interaction]
		#If true, raytraces will be performed on nearby vehicles when left-clicking the mouse, rather than just right-clicking it. This allows one to be damaged/broken when clicking anywhere on it, rather than just on its bounding box.
		enabledLeftClick = true

	#Configuration for display related options
	[client.display]
		#If true, displays a speedometer on the HUD when driving a vehicle
		enabledSpeedometer = true
		#If true, automatically switches to third person when mounting vehicles
		autoPerspective = true
		#If enabled, camera perspective will always be forced back to first person when exiting a vehicle.
		forceFirstPersonOnExit = false
		#If true, an animation is performed while cycling vehicles in the workstation
		workstationAnimation = true
		#The amount of segments to use to render the hose on a gas pump. The lower the value, the better the performance but renders a less realistically looking hose
		#Range: 1 ~ 100
		hoseSegments = 16

		#Configuration for camera related options
		[client.display.camera]
			#If true, uses an improved camera system when riding vehicles. Disabling this option will restore the default camera but it will break the experience of some vehicles. If you do disable this, clearly you don't care about the weeks MrCrayfish spent developing this awesome new camera system and want to hurt your eyes, you've been warned!
			immersiveCamera = false
			#Makes the camera follow the vehicles traveling direction and rotations. This will be limited to yaw if immersiveCamera is disabled.
			followVehicleOrientation = true
			#In third person, uses the vehicle as the focus point rather than the players head. This only has an effect when immersiveCamera is enabled.
			useVehicleAsFocusPoint = true
			#Makes the camera follow vehicle rotations on the x-axis (pitch). This only has an effect when followVehicleOrientation is enabled.
			shouldFollowPitch = false
			#Makes the camera follow vehicle rotations on the y-axis (yaw). This only has an effect when followVehicleOrientation is enabled.
			shouldFollowYaw = true
			#Makes the camera follow vehicle rotations on the z-axis (roll). This only has an effect when followVehicleOrientation is enabled.
			shouldFollowRoll = false

